const actions = {
  ADD_PRODUCT: 'product/ADD_PRODUCT',
  GET_PRODUCTS_BY_CATEGORY: 'product/GET_PRODUCTS_BY_CATEGORY',
  SET_STATE: 'product/SET_STATE',
  ADD_FAVOURITE: 'product/FAVOURITE',
  GET_FAVOURITE: 'product/GET_FAVOURITE',
  GET_OWN_PRODUCTS_BY_STATUS: 'product/GET_OWN_PRODUCTS_BY_STATUS',
  SEARCH_PRODUCTS: 'product/SEARCH_PRODUCTS',
  SEARCH_PRODUCTS_BY_IMAGE: 'PRODUCT/SEARCH_PRODUCTS_BY_IMAGE',
  ADD_REVIEW: 'product/ADD_REVIEW'
}

export default actions
